In [21]:
#Create NumPy arrays with different methods (lists, zeros, ones, arange)
import numpy as np

arr1 = np.array([1,2,3,4,5]) #using list
arr2 = np.zeros((2,2)) #using zeros
arr3 = np.ones((2,2)) #using ones
arr4 = np.arange(0,20,5) #using arange

print(arr1, end="\n\n")
print(arr2, end="\n\n")
print(arr3, end="\n\n")
print(arr4)

[1 2 3 4 5]

[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]]

[ 0  5 10 15]


In [28]:
#Perform mathematical operations on NumPy arrays (addition, subtraction, multiplication, division).
arr1 = np.array([2,4,6,8,10])
arr2 = np.array([1,3,5,7,9])

print("Addition", arr1 + arr2)
print("Subtraction", arr1 - arr2)
print("Multiplication", arr1 * arr2)
print("Division", arr2 / arr1)

Addition [ 3  7 11 15 19]
Subtraction [1 1 1 1 1]
Multiplication [ 2 12 30 56 90]
Division [0.5        0.75       0.83333333 0.875      0.9       ]


In [35]:
#Practice indexing and slicing NumPy arrays.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Indexing first row, thrid element:", arr[0,2])
print("Slicing first 2 rows:\n", arr[:2])
print("Slicing first 2 rows and columns:\n", arr[:2, :2])

Indexing first row, thrid element: 3
Slicing first 2 rows:
 [[1 2 3]
 [4 5 6]]
Slicing first 2 rows and columns:
 [[1 2]
 [4 5]]


In [41]:
# Use NumPy functions for basic statistical analysis like mean,median and mode.
from scipy import stats
arr = np.array([1,2,3,4,5,6,7,7,8,9])

print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("Mode: ", stats.mode(arr)[0])

Mean:  5.2
Median:  5.5
Mode:  [7]


In [48]:
#Experiment with reshaping and transposing NumPy arrays
arr = np.array([[1,2],[3,4],[5,6]])

print("Reshaped array:\n", arr2)

Reshaped array:
 [[1 2 3]
 [4 5 6]]
